package com.barangay.clearance.shared.audit;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Immutable record of a state-changing operation performed in the system.
 *
 * <p>
 * Maps to the {@code audit_logs} table created by
 * {@code V1__initial_schema.sql}.
 * No setters are exposed — once written, an audit record must never be mutated.
 * </p>
 */
@Entity
@Table(name = "audit_logs")
@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class AuditLog {

    /** Surrogate primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * The user who performed the action; {@code null} for unauthenticated events
     * (e.g. a failed login attempt by an unknown email).
     */
    @Column(name = "user_id")
    private UUID userId;

    /**
     * Action constant — one of the values defined in {@link AuditAction}.
     * Maximum 100 characters.
     */
    @Column(name = "action", nullable = false, length = 100)
    private String action;

    /**
     * The domain entity type this event relates to (e.g.
     * {@code "ClearanceRequest"},
     * {@code "User"}, {@code "Resident"}). Maximum 50 characters.
     */
    @Column(name = "entity_type", length = 50)
    private String entityType;

    /** The primary key of the affected entity. */
    @Column(name = "entity_id")
    private UUID entityId;

    /**
     * Human-readable or JSON-structured description of what changed.
     * Stored as TEXT — no length limit at the application layer.
     */
    @Column(name = "details", columnDefinition = "TEXT")
    private String details;

    /**
     * IP address of the originating request. Supports both IPv4 ({@code x.x.x.x})
     * and IPv6 addresses (max 45 characters). {@code null} for background jobs or
     * when no HTTP context is available.
     */
    @Column(name = "ip_address", length = 45)
    private String ipAddress;

    /** Timestamp set by the database default on insert. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
